# model
num_joints: 17
model_name: "CPM.model"

# dataset
data_path: "data/val"
batch_size: 16
img_size: 384
sigma: 3

# hyperparameters
epochs: 50
learning_rate: 0.001

# loss
use_joints_weight: True
