# model
num_joints: 17
model_name: "CPM.model"

# dataset
data_path: "data/val"
batch_size: 16
img_size: 384
stride: 4
sigma: 3

# hyperparameters
learning_rate: 0.001
weight_decay: 0.0005
momentum: 0.9
epochs: 50
