# model
num_joints: 17
model_type: "custom"
model_name: "CPM10.model"

# dataset
data_path: "data/train"
batch_size: 16
img_size: 384
sigma: 3

# hyperparameters
epochs: 30
learning_rate: 0.001

# loss
use_joints_weight: True

# augmentation
preprocess:
  rotate: True
  horizontal_flip: True
  hsv: True
