# model
num_joints: 17
model_type: "CPHRNetv2"
model_name: "CPHRNetv2"
num_channels: 48 # this parameter will not be used if CPM is specified

# dataset
data_path: ["data/train", "data/val"]
batch_size: 32
img_size: 256
sigma: 2

# hyperparameters
epochs: 50
learning_rate: 0.0002

# loss
use_joints_weight: True

# augmentation
preprocess:
  train:
    rotate: True
    scale: True
    horizontal_flip: True
    hsv: True
  valid:
    rotate: False
    scale: False
    horizontal_flip: False
    hsv: False
