# model
num_joints: 17
model_type: "CPM"
model_name: "test.model"

# dataset
data_path: "data/train"
batch_size: 16
img_size: 384
sigma: 3

# hyperparameters
epochs: 30
learning_rate: 0.001

# loss
use_joints_weight: True
